name: MATTLCOX
favicon: null
layout_spectrum: 0.7665068102069199
typography_spectrum: 0.022272173315286636
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.605079751694575
  lightness: 0.4546678336337209
  saturation: 0.7969239198137075
  rhythmicContrast: 0.6066742879338562
purpose: []
