name: MATTHEW L COX
favicon: null
layout_spectrum: 0.01085
typography_spectrum: 0.98915
title: 'Entrepreneur, Speaker, Coach'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#606060'
    - '#c50813'
    - '#ccb4b3'
    - '#f5f5f5'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
