name: MATTHEW L COX
favicon: null
layout_spectrum: 0.99917
typography_spectrum: 0.06093
title: 'Entrepreneur, Speaker, Coach'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ea3b1a'
    - '#6e6e6e'
    - '#000000'
    - '#fbb536'
    - '#ffffff'
  brandStrength: 1
  lightness: 0
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
