name: MATTHEW L COX
favicon: null
layout_spectrum: 1
typography_spectrum: 0.98915
title: 'Entrepreneur, Speaker, Coach'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b19776'
    - '#3e3222'
    - '#746047'
    - '#e8d2ba'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
